'use strict';

angular.module('benwalfordApp')
  .factory('Cell', function(){

    var live = '*';
    var dead = 'o';

    var Cell = function (state) {
      this.state = state;

      this.toggle = function() {
        if (this.state === dead) {
          this.state = live;
        } else {
          this.state = dead;
        }
      };
    };

    // var initialState = [
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    // ];

    // var initialState = [
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    //   [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    // ];

    var initialState = [
      [(new Cell(live)),(new Cell(live)), (new Cell(live)), (new Cell(live)),(new Cell(live)),],
      [(new Cell(live)),(new Cell(live)), (new Cell(live)), (new Cell(live)),(new Cell(live)),],
      [(new Cell(live)),(new Cell(live)), (new Cell(live)), (new Cell(live)),(new Cell(live)),],
      [(new Cell(live)),(new Cell(live)), (new Cell(live)), (new Cell(live)),(new Cell(live)),],
      [(new Cell(live)),(new Cell(live)), (new Cell(live)), (new Cell(live)),(new Cell(live)),],
    ];

    return initialState;
  });
