'use strict';

angular.module('benwalfordApp')
.factory('World', function(){

  var live = 'o';
  var dead = '*';

  var Cell = function (state) {
    this.state = state;

    this.toggle = function() {
      if (this.state === dead) {
        return live;
      } else {
        return dead;
      }
    };
  };

  var initialState = [
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(live)),(new Cell(live)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
    [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
  ];

  // var initialState = [
  // [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
  // [(new Cell(live)),(new Cell(live)),(new Cell(live)),],
  // [(new Cell(dead)),(new Cell(dead)),(new Cell(dead)),],
  // ];

  function build(state){
    var structure = [];

    for (var i = 0; i < state.length; i++) {
      structure.push([]);
    }

    return structure;
  }

  var structure = build(initialState);

  return {
    buildCell: Cell,
    alive: live,
    dead: dead,
    emptyStructure: structure,
    initialState: initialState,
  };
});
