'use strict';

angular.module('benwalfordApp')
.factory('World',['Cell', 'State', function(Cell, State){

  var initialState = [
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.live)),(new Cell(State.live)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
    [(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),(new Cell(State.dead)),],
  ];

  function build(state){
    var structure = [];
    for (var i = 0; i < state.length; i++) {
      structure.push([]);
    }
    return structure;
  }

  function emptyStructure() {
    return build(initialState);
  }

  return {
    initialState: initialState,
    get emptyStructure() { return emptyStructure(); },
  };

}]);
