default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: benwalford_development

test:
  <<: *default
  database: benwalford_test

production:
  <<: *default
  database: benwalford_production
  username: benwalford
  password: <%= ENV['BENWALFORD_PASSWORD'] %>
